version: '2'
services:
  php:
    container_name: secture-php
    image: secture-php
    build: php
    links:
      - db
    volumes:
      - ${APP_DIR}:/home/app:cached
    network_mode: bridge
  web:
    container_name: secture-web
    image: secture-web
    build: web
    links:
      - php
    volumes_from:
      - php
    ports:
      - ${APP_PORT}:80
    network_mode: bridge
  db:
    container_name: secture-db
    image: mariadb:10.2.7
    volumes:
      - ${APP_DB}:/var/lib/mysql
      - ${PWD}/db/etc/mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    network_mode: bridge